[loggers]
keys=root,r4nger

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=standardFormatter

[logger_root]
level=INFO
handlers=consoleHandler

[logger_r4nger]
level=INFO
handlers=consoleHandler,fileHandler
qualname=r4nger
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=standardFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=INFO
formatter=standardFormatter
args=('logs/r4nger.log', 'a')

[formatter_standardFormatter]
format=%(asctime)s [%(levelname)s] %(name)s: %(message)s
